---

name: "Self Test"
run-name: "Self Test workflow started by @${{ github.actor }}"

on:
  push:

jobs:
  run-self:
    name: Run fmtya on itself
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run fmtya
        uses: ./
        with:

          # permission settings
          token: ${{ secrets.GITHUB_TOKEN }}

          # commit information
          commit-user-name: norwd
          commit-user-email: 106889957+norwd@users.noreply.github.com
          signing-private-key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_FMTYA }}
          signing-passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_FMTYA }}

          # yamlfmt configuration
          exclude-files: .github/testing/bad.yml
          include-files: |
            **/*.{yaml,yml}
            .github/testing/nonexisting.yml
